// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-y9ItoYxdWBUYziRFAtUOt662aUgjQg',
    appId: '1:11124029647:web:0902bf32a8a637c3455fba',
    messagingSenderId: '11124029647',
    projectId: 'gymly-e99a0',
    authDomain: 'gymly-e99a0.firebaseapp.com',
    storageBucket: 'gymly-e99a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJmx0bPLGbEtlwX6Zg9Aq46t_cL0boPBo',
    appId: '1:11124029647:android:f09f58bd3fd50855455fba',
    messagingSenderId: '11124029647',
    projectId: 'gymly-e99a0',
    storageBucket: 'gymly-e99a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6XDtgHg3M8z3gehZWc6cLq1kZAAJvV0c',
    appId: '1:11124029647:ios:080fa2dfcaefdc75455fba',
    messagingSenderId: '11124029647',
    projectId: 'gymly-e99a0',
    storageBucket: 'gymly-e99a0.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6XDtgHg3M8z3gehZWc6cLq1kZAAJvV0c',
    appId: '1:11124029647:ios:080fa2dfcaefdc75455fba',
    messagingSenderId: '11124029647',
    projectId: 'gymly-e99a0',
    storageBucket: 'gymly-e99a0.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc-y9ItoYxdWBUYziRFAtUOt662aUgjQg',
    appId: '1:11124029647:web:7a3437e881bfbd54455fba',
    messagingSenderId: '11124029647',
    projectId: 'gymly-e99a0',
    authDomain: 'gymly-e99a0.firebaseapp.com',
    storageBucket: 'gymly-e99a0.firebasestorage.app',
  );
}
